#!/usr/bin/env php
<?php

namespace Dorgflow;

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\DependencyInjection\ContainerBuilder;
//use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

$container = new ContainerBuilder();
// Don't bother with PhpFileLoader; it's overkill.
require 'services.php';

print "Hello, this is Dorgflow!\n";

$application = new Application();

$application->add(new \Dorgflow\Command\SymfCommand());

$application->setDefaultCommand('symfony');

$application->run();

return;
  
// Old code below:  


$command_class_name = CommandResolver::getCommandClass($argv);

$command = $command_class_name::create($container);

try {
  $command->execute();
}
catch (\Exception $e) {
  print $e->getMessage() . "\n";
}
