#!/usr/bin/env php
<?php

namespace Dorgflow;

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\DependencyInjection\ContainerBuilder;

$container = new ContainerBuilder();
// Don't bother with PhpFileLoader; it's overkill.
require 'services.php';

print "Hello, this is Dorgflow!\n";

// Build the console application.
$application = new Application('Dorgflow');

// Register commands.
$application->add($container->get('command.apply'));
$application->add($container->get('command.cleanup'));
$application->add($container->get('command.patch'));
$application->add($container->get('command.status'));
$application->add($container->get('command.open'));
$application->add($container->get('command.diff'));
$application->add($container->get('command.setup'));
$application->add($container->get('command.update'));
$application->add($container->get('command.master'));
$application->add($container->get('command.purge'));

$application->setDefaultCommand('patch');

$application->run();
